- include_tasks: rhel.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Do we have a local vagrant version
  stat:
    path: "/vagrant/platform-setup-x64-linux-{{appdversion}}.sh"
  register: vagrantinstaller

- name: Do we have AppDynamics installer
  stat:
    path: "/var/tmp/platform-setup-x64-linux-{{appdversion}}.sh"
  register: installer

- name: Download AppDynamics installer
  get_url:
    url: "https://www.therapypages.com/sw/platform-setup-x64-linux-{{appdversion}}.sh"
    dest: "/var/tmp/platform-setup-x64-linux-{{appdversion}}.sh"
    owner: root
    group: root
    validate_certs: no
    mode: 0755
  when: not installer.stat.exists and not vagrantinstaller.stat.exists

- name: Set vagrant as run directory
  set_fact:
    runpath: /vagrant
  when: vagrantinstaller.stat.exists

- name: Set /var/tmp as run directory
  set_fact:
    runpath: /var/tmp
  when: installer.stat.exists

- name: Set permissions
  shell: "chmod +x /{{runpath}}/platform-setup-x64-linux-{{appdversion}}.sh"


- name: Create Silent config file
  template:
    src: silent.vars.j2
    dest: /var/tmp/silent.vars
    owner: root
    group: root
    mode: 0600

- name: Install AppDynamics
  shell: "{{runpath}}/platform-setup-x64-linux-{{appdversion}}.sh -q -varfile /var/tmp/silent.vars"
